/**
 * Initial categories seed for Delivra platform.
 * Run: npx ts-node src/database/seeds/initial-categories.seed.ts
 */

export const INITIAL_CATEGORIES = [
  {
    name: 'Food & Dining', slug: 'food-dining', icon_url: '/icons/food.svg',
    metadata: { requires_preparation_time: true, has_dietary_filters: true },
    children: [
      { name: 'Restaurants', slug: 'restaurants' },
      { name: 'Fast Food', slug: 'fast-food' },
      { name: 'Cafe & Coffee', slug: 'cafe-coffee' },
      { name: 'Desserts & Bakery', slug: 'desserts-bakery' },
      { name: 'Healthy & Diet', slug: 'healthy-diet' },
      { name: 'Home Chefs', slug: 'home-chefs' },
      { name: 'Asian Cuisine', slug: 'asian-cuisine' },
      { name: 'Italian', slug: 'italian' },
      { name: 'Middle Eastern', slug: 'middle-eastern' },
      { name: 'Indian', slug: 'indian' },
      { name: 'Mexican', slug: 'mexican' },
      { name: 'Seafood', slug: 'seafood' },
      { name: 'BBQ & Grills', slug: 'bbq-grills' },
      { name: 'Breakfast', slug: 'breakfast' },
      { name: 'Vegan & Vegetarian', slug: 'vegan-vegetarian' },
      { name: 'Pizza', slug: 'pizza' },
      { name: 'Burgers', slug: 'burgers' },
      { name: 'Sushi', slug: 'sushi' },
      { name: 'Chinese', slug: 'chinese' },
      { name: 'Thai', slug: 'thai' },
      { name: 'Korean', slug: 'korean' },
      { name: 'Turkish', slug: 'turkish' },
      { name: 'Lebanese', slug: 'lebanese' },
    ],
  },
  {
    name: 'Grocery', slug: 'grocery', icon_url: '/icons/grocery.svg',
    metadata: { has_weight_variants: true },
    children: [
      { name: 'Supermarket', slug: 'supermarket' },
      { name: 'Fruits & Vegetables', slug: 'fruits-vegetables' },
      { name: 'Meat & Seafood', slug: 'meat-seafood' },
      { name: 'Dairy & Eggs', slug: 'dairy-eggs' },
      { name: 'Organic & Health', slug: 'organic-health' },
      { name: 'Frozen Foods', slug: 'frozen-foods' },
      { name: 'Beverages', slug: 'beverages' },
      { name: 'Snacks', slug: 'snacks-grocery' },
      { name: 'Canned Goods', slug: 'canned-goods' },
      { name: 'Baking Supplies', slug: 'baking-supplies' },
      { name: 'Rice & Pasta', slug: 'rice-pasta' },
      { name: 'Oils & Condiments', slug: 'oils-condiments' },
      { name: 'Baby Food', slug: 'baby-food' },
      { name: 'Bread & Bakery', slug: 'bread-bakery' },
      { name: 'Spices & Herbs', slug: 'spices-herbs' },
      { name: 'Cereals & Breakfast', slug: 'cereals-breakfast' },
      { name: 'Tea & Coffee', slug: 'tea-coffee' },
    ],
  },
  {
    name: 'Pharmacy & Health', slug: 'pharmacy-health', icon_url: '/icons/pharmacy.svg',
    metadata: { requires_prescription_upload: true, age_verification: true },
    children: [
      { name: 'Medicines', slug: 'medicines' },
      { name: 'Personal Care', slug: 'personal-care' },
      { name: 'Baby Care', slug: 'baby-care' },
      { name: 'Supplements & Vitamins', slug: 'supplements-vitamins' },
      { name: 'Medical Devices', slug: 'medical-devices' },
      { name: 'Skincare', slug: 'skincare' },
      { name: 'Oral Care', slug: 'oral-care' },
      { name: 'First Aid', slug: 'first-aid' },
      { name: 'Eye Care', slug: 'eye-care' },
      { name: "Women's Health", slug: 'womens-health' },
      { name: "Men's Health", slug: 'mens-health' },
      { name: 'Elderly Care', slug: 'elderly-care' },
      { name: 'Sexual Wellness', slug: 'sexual-wellness' },
      { name: 'Ayurvedic & Herbal', slug: 'ayurvedic-herbal' },
    ],
  },
  {
    name: 'Flowers & Gifts', slug: 'flowers-gifts', icon_url: '/icons/flowers.svg',
    metadata: { has_occasion_tags: true, gift_wrapping: true },
    children: [
      { name: 'Bouquets', slug: 'bouquets' },
      { name: 'Gift Baskets', slug: 'gift-baskets' },
      { name: 'Chocolates', slug: 'chocolates' },
      { name: 'Cakes', slug: 'cakes' },
      { name: 'Greeting Cards', slug: 'greeting-cards' },
      { name: 'Balloons', slug: 'balloons' },
      { name: 'Luxury Flowers', slug: 'luxury-flowers' },
      { name: 'Wedding Flowers', slug: 'wedding-flowers' },
      { name: 'Sympathy Flowers', slug: 'sympathy-flowers' },
      { name: 'Birthday Gifts', slug: 'birthday-gifts' },
      { name: 'Anniversary Gifts', slug: 'anniversary-gifts' },
      { name: 'Plants & Succulents', slug: 'plants-succulents' },
      { name: 'Perfumes', slug: 'perfumes-gifts' },
      { name: 'Personalized Gifts', slug: 'personalized-gifts' },
    ],
  },
  {
    name: 'Pet Supplies', slug: 'pet-supplies', icon_url: '/icons/pets.svg',
    metadata: { pet_type_filter: true },
    children: [
      { name: 'Dog Food', slug: 'dog-food' },
      { name: 'Cat Food', slug: 'cat-food' },
      { name: 'Pet Accessories', slug: 'pet-accessories' },
      { name: 'Pet Grooming', slug: 'pet-grooming' },
      { name: 'Pet Medicines', slug: 'pet-medicines' },
      { name: 'Pet Toys', slug: 'pet-toys' },
      { name: 'Beds & Furniture', slug: 'pet-beds-furniture' },
      { name: 'Fish & Aquarium', slug: 'fish-aquarium' },
      { name: 'Bird Supplies', slug: 'bird-supplies' },
      { name: 'Small Animal Supplies', slug: 'small-animal-supplies' },
      { name: 'Pet Treats', slug: 'pet-treats' },
    ],
  },
  {
    name: 'Packages & Courier', slug: 'packages-courier', icon_url: '/icons/package.svg',
    metadata: { requires_pickup_address: true, weight_limit: true },
    children: [
      { name: 'Send Package', slug: 'send-package' },
      { name: 'Document Delivery', slug: 'document-delivery' },
      { name: 'Pick & Drop', slug: 'pick-drop' },
      { name: 'Same Day Delivery', slug: 'same-day-delivery' },
      { name: 'Express Delivery', slug: 'express-delivery' },
      { name: 'International Shipping', slug: 'international-shipping' },
      { name: 'Furniture Moving', slug: 'furniture-moving' },
      { name: 'Return & Exchange', slug: 'return-exchange' },
    ],
  },
  {
    name: 'Convenience Store', slug: 'convenience-store', icon_url: '/icons/store.svg',
    metadata: {},
    children: [
      { name: 'Snacks & Drinks', slug: 'snacks-drinks' },
      { name: 'Home Essentials', slug: 'home-essentials' },
      { name: 'Stationery', slug: 'stationery' },
      { name: 'Cleaning Supplies', slug: 'cleaning-supplies' },
      { name: 'Batteries & Electronics', slug: 'batteries-electronics' },
      { name: 'Ice Cream', slug: 'ice-cream' },
      { name: 'Ready to Eat', slug: 'ready-to-eat' },
      { name: 'Tobacco & Smoking', slug: 'tobacco-smoking' },
      { name: 'Newspapers & Magazines', slug: 'newspapers-magazines' },
    ],
  },
  {
    name: 'Shopping', slug: 'shopping', icon_url: '/icons/shopping.svg',
    metadata: { has_size_variants: true, has_color_variants: true },
    children: [
      { name: 'Electronics', slug: 'electronics' },
      { name: 'Mobile & Accessories', slug: 'mobile-accessories' },
      { name: 'Fashion - Men', slug: 'fashion-men' },
      { name: 'Fashion - Women', slug: 'fashion-women' },
      { name: 'Fashion - Kids', slug: 'fashion-kids' },
      { name: 'Home & Kitchen', slug: 'home-kitchen' },
      { name: 'Sports & Fitness', slug: 'sports-fitness' },
      { name: 'Books & Media', slug: 'books-media' },
      { name: 'Toys & Games', slug: 'toys-games' },
      { name: 'Jewelry & Watches', slug: 'jewelry-watches' },
      { name: 'Beauty & Fragrance', slug: 'beauty-fragrance' },
      { name: 'Bags & Luggage', slug: 'bags-luggage' },
      { name: 'Shoes & Footwear', slug: 'shoes-footwear' },
      { name: 'Computers & Laptops', slug: 'computers-laptops' },
      { name: 'Gaming', slug: 'gaming' },
    ],
  },
  {
    name: 'Home Services', slug: 'home-services', icon_url: '/icons/home-services.svg',
    metadata: { requires_scheduling: true, service_type: true },
    children: [
      { name: 'Cleaning', slug: 'cleaning-service' },
      { name: 'Plumbing', slug: 'plumbing' },
      { name: 'Electrical', slug: 'electrical' },
      { name: 'AC & Appliance Repair', slug: 'ac-appliance-repair' },
      { name: 'Painting', slug: 'painting' },
      { name: 'Pest Control', slug: 'pest-control' },
      { name: 'Laundry & Dry Cleaning', slug: 'laundry-dry-cleaning' },
      { name: 'Carpentry', slug: 'carpentry' },
      { name: 'Gardening', slug: 'gardening' },
      { name: 'Car Wash', slug: 'car-wash' },
      { name: 'Handyman', slug: 'handyman' },
    ],
  },
  {
    name: 'Water & Gas', slug: 'water-gas', icon_url: '/icons/water-gas.svg',
    metadata: { bulk_order: true },
    children: [
      { name: 'Water Delivery', slug: 'water-delivery' },
      { name: 'Gas Cylinder', slug: 'gas-cylinder' },
      { name: 'Fuel Delivery', slug: 'fuel-delivery' },
      { name: 'Ice Delivery', slug: 'ice-delivery' },
    ],
  },
];

// Seed runner (run directly with ts-node)
async function seed() {
  console.log('Category seed data ready. Import INITIAL_CATEGORIES and use in your seeder.');
  console.log(`Total top-level categories: ${INITIAL_CATEGORIES.length}`);
  const totalSub = INITIAL_CATEGORIES.reduce((sum, c) => sum + (c.children?.length || 0), 0);
  console.log(`Total sub-categories: ${totalSub}`);
  console.log(`Total categories: ${INITIAL_CATEGORIES.length + totalSub}`);
}

seed();
